version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: aquabeacon-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: aquabeacon
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - aquabeacon-network

  minio:
    image: minio/minio
    container_name: aquabeacon-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - aquabeacon-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  server:
    build:
      context: ../server
      dockerfile: Dockerfile
    container_name: aquabeacon-server
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://admin:password@mongodb:27017/aquabeacon?authSource=admin
      JWT_SECRET: your-jwt-secret-change-in-production
      JWT_REFRESH_SECRET: your-refresh-secret-change-in-production
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_REGION: us-east-1
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: aquabeacon
      CLIENT_URL: http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - minio
    networks:
      - aquabeacon-network
    volumes:
      - ../server:/app
      - /app/node_modules

  client:
    build:
      context: ../client
      dockerfile: Dockerfile
    container_name: aquabeacon-client
    environment:
      VITE_API_BASE_URL: http://localhost:5000/api
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - aquabeacon-network
    volumes:
      - ../client:/app
      - /app/node_modules

volumes:
  mongodb_data:
  minio_data:

networks:
  aquabeacon-network:
    driver: bridge